apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-role
subjects:
  - kind: ServiceAccount
    name: postgres-sa
