apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  postgres-user: postgres
  postgres-password: postgres
  replication-user: replicator
  replication-password: replicapass
